### ISSUE TITLE
Allow other elixir plugins to modify the real webpack config

### ISSUE THREAD

**Issue by yyx990803** [JeffreyWay/laravel-elixir-webpack-official#11]
I'm playing around with a Vue 2.0 plugin (similar to `laravel-elixir-vue`) but noticed that `Elixir.config.js.webpack` only allows modifying the loaders rather than the entire webpack config. This can be quite limiting since the plugin may need to inject some extra config (e.g. `resolve.alias` or `vue-loader` config).

**Comment by laracasts** [comment]
Elixir should read any webpack.config.js file that you have in your project
root.

**Comment by yyx990803** [comment]
This is not for the end user, but for other plugins. The ideal experience for the Vue plugin is the user does `npm install laravel-elixir-vue`, require it in `gulpfile.js` and be done, instead of having to add extra webpack config. However currently loaders is the only option that can be modified by a plugin.

**Comment by JeffreyWay** [comment]
Do you think something like this would be fine for your plugin?

``` js
Elixir.webpack.mergeConfig({
    babel: {
        presets: ['es2015'],
        plugins: ['add-module-exports', 'transform-runtime'],
    },
    module: {
        loaders: [{
            test: /\.vue$/,
            loader: 'vue'
        }]
    }
});  
```

Behind the scenes, that would do a deep extend of the default config we provide. If so, I'll add it today.

**Comment by JeffreyWay** [comment]
Okay, that's done and pushed. Use `Elixir.webpack.mergeConfig()` to set your plugin's config.

**Comment by yyx990803** [comment]
👍 thanks!

**Comment by lukepolo** [comment]
needed this, thank you!

**Comment by anteriovieira** [comment]
Thanks, this is very useful for me.
