### ISSUE TITLE
How to set webpack publicPath

### ISSUE THREAD

**Issue by tripper54** [JeffreyWay/laravel-elixir-webpack-official#12]
Webpack is compiling the images in my Vue components OK, and saving them to public/js .

But the image path printed doesn't include the js/ prefix, it's just the compiled filename. So the output in the browser shows a broken image. 

How do I set the webpack publicPath property to fix this?

I have tried 

``` js
Elixir.webpack.mergeConfig({
    module: {
        output: {
            publicPath: 'js/',
        },
        loaders: [
            {
                test: /\.svg$/,
                loader: 'file',
            },
        ],
    }
});
```

But it seems the value for publicPath is being ignored.

**Comment by grusch-it** [comment]
Try to add `__webpack_public_path__ = '/js/'` on top of `resources/assets/js/app.js`:

``` js
// app.js

__webpack_public_path__ = '/js/'

// ...

require('./bootstrap')

// ...
```

**Comment by srph** [comment]
It shouldn't be under the `module` object.

``` diff
Elixir.webpack.mergeConfig({
+  output: {
+      publicPath: 'js/',
+  },
    module: {
-        output: {
-            publicPath: 'js/',
-        },
        loaders: [
            {
                test: /\.svg$/,
                loader: 'file',
            },
        ],
    }
});
```

**Comment by tripper54** [comment]
thanks, my bad!
