### ISSUE TITLE
Possible breaking changes introduced in Webpack 2.1.0-beta23

### ISSUE THREAD

**Issue by AndrewFeeney** [JeffreyWay/laravel-elixir-webpack-official#17]
I can't get my gulp build to run. The error states:

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'babel'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
```

Some googling indicates that this might be related to breaking changes in Webpack 2.1.0-beta23, but I don't really know.

Related github issues:

https://github.com/webpack/webpack/issues/3018
https://github.com/angular/angular-cli/issues/2234

**Comment by joseconsador** [comment]
Having the same issue.

**Comment by jenky** [comment]
My workaround is installed beta22 version

`npm i webpack@2.1.0-beta.22`

**Comment by developerdino** [comment]
I'm having the same issue. Thanks @jenky for the workaround.

**Comment by TheLarkInn** [comment]
https://github.com/webpack/webpack/issues/3018#issuecomment-248231784

**Comment by usulix** [comment]
> My workaround is installed beta22 version

npm i webpack@2.1.0-beta.22

This does not fix the issue for elixir's laravel-elixir-webpack-official does it?
Am I missing something or are you manually running webpack in your gulpfile.js?

**Comment by AndrewFeeney** [comment]
I've submitted a PR for a patch to lock down the dependency to a max of webpack@2.1.0-beta.22 until the actual issue with the breaking changes is fixed. Hopefully someone more familiar with node than I can look into the changes required to make the package compatible with beta23.

**Comment by rsm23** [comment]
same issue here 

> /node_modules/webpack/lib/webpack.js:16
>         throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
>         ^
> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> - configuration has an unknown property 'babel'. These properties are valid:
>   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
>   at webpack (/Users/pc/projects/dmca/node_modules/webpack/lib/webpack.js:16:9)
>   at Stream.<anonymous> (/Users/pc/projects/dmca/node_modules/webpack-stream/index.js:131:20)
>   at _end (/Users/pc/projects/dmca/node_modules/through/index.js:65:9)
>   at Stream.stream.end (/Users/pc/projects/dmca/node_modules/through/index.js:74:5)
>   at DestroyableTransform.onend (/Users/pc/projects/dmca/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
>   at DestroyableTransform.g (events.js:286:16)
>   at emitNone (events.js:91:20)
>   at DestroyableTransform.emit (events.js:185:7)
>   at /Users/pc/projects/dmca/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
>   at _combinedTickCallback (internal/process/next_tick.js:67:7)

**Comment by AndrewFeeney** [comment]
@rsm23 Can you run 'npm update' and try again? A patch was merged a few hours ago.

**Comment by rsm23** [comment]
@WebSpanner actually it has been fixed, thank you so much

**Comment by aeron11** [comment]
I tried these  steps and finally it works:

npm uninstall webpack --save-dev

then

npm install webpack@2.1.0-beta.22 --save-dev

**Comment by jbuican14** [comment]
I ran into this issue today : 

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

> - configuration.output.path: The provided value "build" is not an absolute path!

Then I tried the above solution : npm install webpack@2.1.0-beta.22 --save-dev and it works! thanks
