### ISSUE TITLE
[Question] What is the right way to add custom loaders?

### ISSUE THREAD

**Issue by ikoolik** [JeffreyWay/laravel-elixir-webpack-official#2]
I'm using structures like `let template = require('./component.html`)`. For this to work I use 'raw-loader' for webpack.

The question is: What is a **right** way to configure custom loaders while using laravel-elixir?

Before webpack related code was extracted, I have simply modified elixir.config object to fit my needs. Like this:

```
elixir.config.js.webpack.loaders.push({ test: /\.html$/, loader: 'raw' });
```

But this approach doesn't work any longer.

I can define my own `webpack.config.js`, but it doesn't look like a right thing to do since It fully overrides default loaders and I will have to copy `{ test: /\.js/, loader: 'buble' }` there as well.

Any thoughts on the subject are very much appreciated.
Thanks.

**Comment by JeffreyWay** [comment]
You could:
1. Add webpack config as the fourth argument to mix.webpack()
2. Create a webpack.config.js file, as you noted.
3. Do:

```
elixir.ready(function () {
  // elixir.config.js.webpack...
});
```
1. Set your config within the Elixir callback.

```
elixir(function (mix) {
    // elixir.config.js...
});
```

```
```

**Comment by PascaleBeier** [comment]
Maybe someone finds this helpful - I used the expose-loader to expose jQuery as a window object this way:

``` javascript
elixir.ready(() => {
    elixir.config.js.webpack = {
        loaders: [
            { test: require.resolve('jquery'), loader: 'expose?jQuery!expose?$' }
        ],
    }
})

elixir(mix => {
    mix.webpack('backend.js')
        .sass('backend.scss')
})
```

working great!
