### ISSUE TITLE
Npm install breaks

### ISSUE THREAD

**Issue by Jarinus** [JeffreyWay/laravel-elixir-webpack-official#36]
Hello,

When attempting to run `npm install` from a fresh 5.3 Laravel install I noticed it would break when attempting to install this package. The reason is pretty simple:

`Error: No compatible version found: webpack@'>=2.1.0-beta.15 <=2.1.0--beta.22'`

If you look closely it says `2.1.0--beta.22` instead of `2.1.0-beta.22`. Now, I've cloned your source to see if I would be able to change it myself, but I've not seen that syntax before so I'd rather make an issue about it.

**Comment by JeffreyWay** [comment]
What do you get for `node -v` and `npm -v`?

**Comment by philtweir** [comment]
I found the same issue after installing node from my distribution repo - the npm version number was 1.4.21. Upgrading npm resolved this for me (tested with 3.10.9 and 2.15.9)

**Comment by Jarinus** [comment]
@philtweir and @JeffreyWay Thanks, I'll check out if that fixes the issue.

**Comment by Jarinus** [comment]
Running `sudo npm install npm -g` fixed the issue. I was using 1.3.x.
