### ISSUE TITLE
Hot Module Replacement

### ISSUE THREAD

**Issue by petecoop** [JeffreyWay/laravel-elixir-webpack-official#44]
I've just spent an evening trying to set up HMR with this but haven't got it working, ideally I think it should launch `webpack-dev-server` within gulp, but I've only spent tonight with webpack really, I didn't find setting this up that difficult with browserify...

Can anyone help? Are any changes needed to this repo to support HMR?

**Comment by Fgruntjes** [comment]
Same question here, can't get HMR to work. Any suggestions on the configuration for this?

**Comment by kmcluckie** [comment]
I was struggling with the same thing and just discovered Laravel 5.4's new Mix (replacement for Elixir). I've just set it up on an existing 5.3 installation using the instructions here: https://github.com/JeffreyWay/laravel-mix/tree/master/docs

**Comment by petecoop** [comment]
I ended up just using the vue cli to generate some setup and using that instead of Elixir. Mix sounds like it'd work as it's just a wrapper around webpack
